SistemaMedico/Models/AtletaView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace SistemaMedico.Models
{
    [DataContract(IsReference = true)]
    public class AtletaView
    {
        public Datos_Atleta Model { get; set; }

        [Display(Name = "Foto Atleta")]
        public HttpPostedFileBase ImageFile { get; set; }



        // public List<Atleta_Categoria> categorias { get; set; }
        public virtual Equipo_Deportivo equip { get; set; }
    }
}

SistemaMedico/Models/ViewModel/Actualizar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SistemaMedico.Models.ViewModel
{
    public class Actualizar
    {       
        public Datos_Atleta DA { get; set; }
        public Historial_Medico HM { get; set; }
        public Historia_Familiar HF { get; set; }
        public Aparato_Locomotor AL { get; set; }
        public Carrera_Deportiva CD { get; set; }
        public Carrera_Deportiva_Evento CDE { get; set; }
        public Carrera_Deportiva_Familiar CDF { get; set; }
        public Situacion_Laboral SL { get; set; }
        public Apoyo_Economico AE { get; set; }
        public Informacion_Familiar IF { get; set; }
        public Educacion ED { get; set; }
        public Medicamentos ME { get; set; }
        public Habitos HATOS { get; set; }
        public Habitacion HACION { get; set; }
        public Alergias ALAS { get; set; }
        //public List<Element> Elements { get; set; }
    }

}

SistemaMedico/Models/ViewModel/MostrarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaMedico.Models.ViewModel
{
    public class MostrarViewModel
    {
        //public Datos_Atleta DA { get; set; }
        //public Alergias alergia { get; set; }
        public int ID { get; set; }
        public string Foto { get; set; }
        public string Primer_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<System.DateTime> Fecha_De_Registro { get; set; }
        public string Genero { get; set; }
        public string Numero_De_Cedula { get; set; }
        public string Correo_Electronico { get; set; }
        public string Telefono_Convencional { get; set; }
        public string Telefono_Celular { get; set; }
        public string Tiene_Seguro { get; set; }
        public string Hospital { get; set; }
        public string Dirreccion { get; set; }
        public int Municipio { get; set; }
        public string Nombre_Madre { get; set; }
        public string Telefono_Madre { get; set; }
        public string Nombre_Padre { get; set; }
        public string Telefono_Padre { get; set; }
        public string Emergencia { get; set; }
        public string Dirreccion_Emergencia { get; set; }
        public string Embarazo { get; set; }
        public Nullable<bool> Activo { get; set; }

    }
}

SistemaMedico/Controllers/AtletaController.cs
//using SistemaMedico.Clases;
using SistemaMedico.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using SistemaMedico.Models.ViewModel;
using System.Globalization;
using System.IO;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Web;
using System.Web.Helpers;

namespace SistemaMedico.Controllers
{
    public class AtletaController : Controller
    {
        private MeSysEntities db = new MeSysEntities();
        DAL objdal = new DAL();

        // GET: Atleta
        public ActionResult Index()
        {
            IEnumerable<Datos_Atleta> Atleta = db.Datos_Atleta.Where(s => s.Activo.ToString() == "true");
            IEnumerable<Equipo_Deportivo> equipo = db.Equipo_Deportivo.Where(s => s.Activo.ToString() == "true");

            Datos_Atleta datos_Atleta = db.Datos_Atleta
              .Include(x => x.Atleta_Categoria).
              Include(x=>x.Equipo_Deportivo)
              .Where(x => x.ID == x.ID).FirstOrDefault();
            if (datos_Atleta == null)
            {
                return HttpNotFound();
            }
            CargarListasVistaAtleta(datos_Atleta);

            foreach (Atleta_Categoria atleta_Categoria in datos_Atleta.Atleta_Categoria)
            {
                atleta_Categoria.Categorias.Deporte = db.Deporte.Find(atleta_Categoria.Categorias.ID_Deporte);
            }

            ViewBag.Atleta = Atleta;
            return View();
        }

        // GET: Atleta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Datos_Atleta datos_Atleta = db.Datos_Atleta.Find(id);
            if (datos_Atleta == null)
            {
                return HttpNotFound();
            }
            return View(datos_Atleta);
        }

        // GET: Atleta/Create
        public ActionResult Crear()
        {
            CargarListasVistaAtleta(null);
            return View("/Views/Atleta/Crear.cshtml", new AtletaView() { Model = new Datos_Atleta() });
        }

        private void CargarGeneros()
        {
            IEnumerable<SelectListItem> items = new List<SelectListItem>() { new SelectListItem() { Text = "Masculino", Value = "Masculino" }, new SelectListItem() { Text = "Femenino", Value = "Femenino" } };
            ViewBag.Genero = items;
        }


        //hospital

        // POST: Atleta/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(AtletaView view)
        {
            TextInfo myTI = new CultureInfo("en-US", false).TextInfo;
            if (db.Datos_Atleta.Any(x=>x.Numero_De_Cedula==view.Model.Numero_De_Cedula))
            {

            }
            else
            {
                var pic = string.Empty;
                //var folder = "Perfiles";

                if (view.ImageFile != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(view.ImageFile.FileName);
                    string extension = Path.GetExtension(view.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    pic = fileName;
                    //Image Img2 = ResizeImage(100, 100,pic);
                    pic = string.Format("{0}/{1}", "Perfiles", pic);
                    view.ImageFile.SaveAs(Path.Combine(Server.MapPath("/Perfiles"), fileName));
                }

                Datos_Atleta datos_Atleta = new Datos_Atleta();
                datos_Atleta.Foto = pic;
                

                datos_Atleta.Primer_Nombre = myTI.ToTitleCase(view.Model.Primer_Nombre);
                datos_Atleta.Segundo_Nombre = myTI.ToTitleCase(view.Model.Segundo_Nombre);
                datos_Atleta.Primer_Apellido = myTI.ToTitleCase(view.Model.Primer_Apellido);
                datos_Atleta.Segundo_Apellido = myTI.ToTitleCase(view.Model.Segundo_Apellido);
                datos_Atleta.Nombre_Completo = myTI.ToTitleCase(view.Model.Primer_Nombre + " " + view.Model.Segundo_Nombre + " " + view.Model.Primer_Apellido + " " + view.Model.Segundo_Apellido);
                datos_Atleta.Edad = view.Model.Edad;
                datos_Atleta.Fecha_De_Registro = DateTime.Today;

                if (view.Model.Genero == "Masculino")
                {
                    datos_Atleta.Genero = view.Model.Genero;
                    datos_Atleta.Embarazo = "No";


                }
                else
                {
                    datos_Atleta.Genero = view.Model.Genero;
                    datos_Atleta.Embarazo = view.Model.Embarazo;
                }
                datos_Atleta.Numero_De_Cedula = myTI.ToTitleCase(view.Model.Numero_De_Cedula);
                datos_Atleta.Correo_Electronico = view.Model.Correo_Electronico;
                datos_Atleta.Telefono_Convencional = view.Model.Telefono_Convencional;
                datos_Atleta.Telefono_Celular = view.Model.Telefono_Celular;

                datos_Atleta.Tiene_Seguro = view.Model.Tiene_Seguro;

                datos_Atleta.Hospital = view.Model.Hospital;

                datos_Atleta.Dirreccion = myTI.ToTitleCase(view.Model.Dirreccion);
                datos_Atleta.Municipio = view.Model.Municipio;
                datos_Atleta.Nombre_Madre = myTI.ToTitleCase(view.Model.Nombre_Madre);
                datos_Atleta.Telefono_Madre = view.Model.Telefono_Madre;
                datos_Atleta.Nombre_Padre = myTI.ToTitleCase(view.Model.Nombre_Padre);
                datos_Atleta.Telefono_Padre = view.Model.Telefono_Padre;
                datos_Atleta.Emergencia = myTI.ToTitleCase(view.Model.Emergencia);
                datos_Atleta.Dirreccion_Emergencia = myTI.ToTitleCase(view.Model.Dirreccion_Emergencia);

           
             
                datos_Atleta.Activo = true;

                if (view.Model.Atleta_Categoria != null)
                {
                    foreach (Atleta_Categoria atle in view.Model.Atleta_Categoria)
                    {
                        atle.ID_Atleta = view.Model.ID;
                        
                        atle.Estado = true;
                        db.Atleta_Categoria.AddRange(view.Model.Atleta_Categoria);
                    }


                }


                Equipo_Deportivo equi = new Equipo_Deportivo();

                equi.ID_Atleta = view.Model.ID;

                equi.equipdep = view.equip.equipdep;


                if (view.equip.relaentre == "Inadecuadas")
                {
                    equi.relaentre = view.equip.relaentre;
                    equi.ra_ina_entre = myTI.ToTitleCase(view.equip.ra_ina_entre);
                }
                else
                {
                    equi.relaentre = view.equip.relaentre;
                    equi.ra_ina_entre = "";
                }
                if (view.equip.relacompa == "Inadecuadas")
                {
                    equi.relacompa = view.equip.relacompa;
                    equi.ra_ina_compa = myTI.ToTitleCase(view.equip.ra_ina_compa);
                }
                else
                {
                    equi.relacompa = view.equip.relacompa;
                    equi.ra_ina_compa = "";
                }

                equi.Activo = true;

                db.Equipo_Deportivo.Add(equi);
                db.Datos_Atleta.Add(datos_Atleta);
                db.SaveChanges();
                CargarGeneros();

               

            }

             
                //Hospital();
                return RedirectToAction("Index");
            //}

            //return RedirectToAction("Index");
        }

        //Tal como lo platicas puedes crear un método que regrese un booleano y consumirlo con jQuery Ajax.
        //El método en MVC sería algo así:

public bool TienePropositos(string nombre)
        {
            using (var db = new MeSysEntities())
            {
                return db.Datos_Atleta.Any(x => x.Nombre_Completo == nombre);
            }
        }


        //private void SaveFileToDisk(HttpPostedFileBase file)
        //{
        //    WebImage img = new WebImage(file.InputStream);
        //    if (img.Width > 190)
        //    {
        //        img.Resize(190, img.Height);
        //    }
        //    img.Save(Constants.ProductImagePath + file.FileName);
        //    if (img.Width > 100)
        //    {
        //        img.Resize(100, img.Height);
        //    }
        //    img.Save(Constants.ProductThumbnailPath + file.FileName);
        //}
        //public Image ResizeImage(int newWidth, int newHeight, string stPhotoPath)
        //{
        //    Image imgPhoto = null;
        //    try
        //    {
        //        imgPhoto= Image.FromFile(stPhotoPath);

        //        int sourceWidth = imgPhoto.Width;
        //        int sourceHeight = imgPhoto.Height;

        //        //Consider vertical pics
        //        if (sourceWidth < sourceHeight)
        //        {
        //            int buff = newWidth;

        //            newWidth = newHeight;
        //            newHeight = buff;
        //        }

        //        int sourceX = 0, sourceY = 0, destX = 0, destY = 0;
        //        float nPercent = 0, nPercentW = 0, nPercentH = 0;

        //        nPercentW = ((float)newWidth / (float)sourceWidth);
        //        nPercentH = ((float)newHeight / (float)sourceHeight);
        //        if (nPercentH < nPercentW)
        //        {
        //            nPercent = nPercentH;

SistemaMedico/Views/Atleta/Index.cshtml
@using SistemaMedico.Models
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["ID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
    IEnumerable<Datos_Atleta> Atle = (IEnumerable<Datos_Atleta>)ViewBag.Atleta;

}

<div class="container-fluid">
    @*<div class="block-header">
            <h2>DASHBOARD</h2>
        </div>*@
    <div class="row el-element-overlay">
        <div class="col-md-12">
        </div>
        @foreach (Datos_Atleta oElemento in Atle)
        {
            <div class="col-lg-3 col-md-6">
                <div class="cardnigga">
                    <div class="el-card-item">
                        <div class="el-card-avatar el-overlay-1">
                            <img src="~/@oElemento.Foto" alt="user" />
                            <div class="el-overlay scrl-dwn">
                                <ul class="el-info">
                                    <li><a class="btn default btn-outline image-popup-vertical-fit" href="~/HistorialMedico/Crear/@oElemento.ID"><i class="icon-question"></i></a></li>
                                    <li><a class="btn default btn-outline image-popup-vertical-fit" href="~/HistorialMedico/Actualizar/@oElemento.ID"><i class="icon-eye"></i></a></li>
                                    <li><a class="btn default btn-outline image-popup-vertical-fit" href="~/ExamenFisico/Crear/@oElemento.ID"><i class="mdi mdi-run"></i></a></li>
                                    <li><a class="btn default btn-outline image-popup-vertical-fit" href="~/Lesiones/Index/@oElemento.ID"><i class="material-icons">accessible_forward</i></a></li>
                                    <li><a class="btn default btn-outline image-popup-vertical-fit" href="~/Atleta/Actualizar/@oElemento.ID"><i class="mdi mdi-run"></i></a></li>
                                    @*  <li><a href="#">@Html.ActionLink("madasn",new { controller = "Articles", action = "Details",id = oElemento.ID })</a></li>*@
                                    @*<li><a class="btn default btn-outline" href="javascript:void(0);"><i class="icon-link"></i></a></li>*@
                                </ul>
                            </div>
                        </div>
                        <div class="el-card-content">
                            <h4 class="box-title">@oElemento.Nombre_Completo</h4>
                            <h5>@oElemento.Correo_Electronico</h5>
                            <h5>Deporte</h5>
                            @*Html.ActionLink(article.Title,"Login",  // <-- Controller Name."Item" ,   // <-- ActionMethod new { id=article.ArticleID }, // <-- Route arguments. null  // <-- htmlArguments .. which are none. You need this value //     otherwise you call the WRONG method ... //     (refer to comments, below).)*@
                            @*<button class="btn btn-default" type="button">@Html.ActionLink("madasn", "Crear","ExamenFisico", new {id = oElemento.ID ,nombre=oElemento.Nombre_Completo},new { @class = "" })</button>*@
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

SistemaMedico/Views/Atleta/_Category.cshtml
@using SistemaMedico.Models
@model Atleta_Categoria


<li class="list-group-item d-flex justify-content-between align-items-center show_hide_hover" id="atleta_categoria">
    <input hidden id="ID_Categoria" value="@Model.ID_Categoria" name="categorias[].ID_Categoria" />
    <input hidden id="ID_Atleta" value="@Model.ID_Atleta" name="categorias[].ID_Atleta" />
    <input hidden id="ID" value="@Model.ID" name="categorias[].ID" />
    @($"({(Model.Categorias?.Deporte?.Nombre ?? "")})  {Model.Categorias.Categoria}") <span class="" id="cate" style="color:darkred; cursor:pointer;" onclick="removeCatg('@Url.Action("DeleteAtletaCat", "Atleta", new { id=Model.ID})',this)"> (Eliminar) </span>
    @*<input hidden id="Id_Deporte" value="@Model.Categorias.Deporte.Nombre" name="deportes[].ID_Deporte" />
        @Model.Categorias.Deporte <span class="" id="cate" style="color:darkred; cursor:pointer;"/>*@
</li>