SistemaMedico/Controllers/HomeAdminController.cs
using SistemaMedico.Models;
using SistemaMedico.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace SistemaMedico.Controllers
{
    public class HomeAdminController : Controller
    {
        DAL objdal = new DAL();
        public MeSysEntities db = new MeSysEntities();
        // GET: Home
        // [Authorize]
        public ActionResult Index()
        {
            IEnumerable<Usuarios> User = db.Usuarios.Where(s =>s.Activo.ToString() == "true");
            ViewBag.Usuario = User;
            return View();
        }
        public ActionResult Editar(int id)
        {
            Usuarios model = new Usuarios();
            var otabla = db.Usuarios.Find(id);
            model.ID = otabla.ID;
            model.Nombre = otabla.Nombre;
            model.Correo = otabla.Correo;
            model.Contraseña = otabla.Contraseña;
            model.ID_Rol = otabla.ID_Rol;
            ViewBag.Nombre = model.Nombre;

            // string Rolesstring = "select * from Roles";
            // DataSet ds = new DataSet();
            // List<string> li = new List<string>();
            // DataTable dt = new DataTable();
            // dt = objdal.MyMethod(Rolesstring);
            // List<SelectListItem> Roles = new List<SelectListItem>();
            //// Roles.Add(new SelectListItem { Text = "--Seleccionar Rol--", Value = "0" });
            // foreach (DataRow row in dt.Rows)
            // {
            //     Roles.Add(new SelectListItem { Text = Convert.ToString(row.ItemArray[1]), Value = Convert.ToString(row.ItemArray[1]) });
            // }
            // ViewBag.Roles = Roles;
            return View(model);
        }
        [HttpPost]
        public ActionResult Editar(Usuarios model)
        {
            var ousuario = db.Usuarios.Find(model.ID);
            ousuario.Nombre = model.Nombre;
            ousuario.Correo = model.Correo;
            ousuario.Contraseña = SHA256(model.Contraseña.ToString());
            ousuario.ID_Rol = model.ID_Rol;
            db.Entry(ousuario).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return Redirect("~/HomeAdmin/");
        }
        public ActionResult Nuevo()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(UsuarioViewModel model)
        {
            Usuarios ousuario = new Usuarios();
            ousuario.Nombre = model.Nombre;
            ousuario.Correo = model.Correo;
            ousuario.Contraseña = SHA256(model.Contraseña.ToString());
            ousuario.ID_Rol = model.ID_Rol;
            ousuario.Activo = true;
            db.Usuarios.Add(ousuario);
            db.SaveChanges();
            return Redirect("~/HomeAdmin/");
            //asp me la pela
            //x2
            //x3
            //x4
            //x5
        }
        public static List<SelectListItem> GetDropDown()
        {
            MeSysEntities db1 = new MeSysEntities();
            List<SelectListItem> ls = new List<SelectListItem>();
            var lm = db1.Roles.ToList();
            ls.Add(new SelectListItem { Text = "--Seleccionar Rol--", Value = "0" });
            foreach (var temp in lm)
            {
                ls.Add(new SelectListItem() { Text = temp.Rol, Value = temp.ID.ToString() });
            }
            return ls;
        }
        public static string SHA256(string str)
        {
            SHA256 sha256 = SHA256Managed.Create();
            ASCIIEncoding encoding = new ASCIIEncoding();
            byte[] stream = null;
            StringBuilder sb = new StringBuilder();
            stream = sha256.ComputeHash(encoding.GetBytes(str));
            for (int i = 0; i < stream.Length; i++) sb.AppendFormat("{0:x2}", stream[i]);
            return sb.ToString();
        }
        [HttpGet]
        public ActionResult Eliminar(int ID)
        {
            var ousuario = db.Usuarios.Find(ID);
            ousuario.Activo = false;
            db.Entry(ousuario).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return Redirect("~/HomeAdmin/");
        }
    }
}

SistemaMedico/Views/HomeAdmin/Editar.cshtml
@model SistemaMedico.Models.Usuarios
@{
    ViewBag.Title = "Editar Usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //if (Session["ID"] == null)
    //{
    //    Response.Redirect("~/Login/Index");
    //}
    //IEnumerable<Usuario> Usuarios = (IEnumerable<Usuario>)ViewBag.Usuario;
}
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2 style="text-transform:uppercase;">@ViewBag.title @ViewBag.Nombre </h2>
            </div>
            <div class="body">
                @using (Html.BeginForm("Editar", "HomeAdmin", FormMethod.Post))
                {
                    //asjkdhasjkhdasjkh
                    <div class="row">
                        <div class="col-md-12">
                            @Html.HiddenFor(d => d.ID)
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            @Html.LabelFor(d => d.Nombre, new { @class = "form-label" })
                                            @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>

                                @*@Html.ValidationMessageFor(d => d.UserName, null, new { @class = "red" })*@
                            </div>
                            @* Correo *@
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            @Html.LabelFor(d => d.Correo, new { @class = "form-label" })
                                            @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "red" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @* Contraeña *@
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            @Html.LabelFor(d => d.Contraseña, new { @class = "form-label" })
                                            @Html.PasswordFor(d => d.Contraseña, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(d => d.Contraseña, null, new { @class = "danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-float">

                                        @Html.Label("Rol") <br />
                                        @Html.DropDownListFor(x => x.ID_Rol, SistemaMedico.Controllers.HomeAdminController.GetDropDown(), new { @class = "form-control" })
                                        @*@Html.DropDownListFor(d => d.ID_Rol, new SelectList(ViewBag.Roles, "Value", "Text"), new { @class = "form-control p-0" })*@
                                        @*@Html.DropDownListFor(model => model.ID_Rol, ViewBag.Roles as List<SelectListItem>, "ID", "Rol", "- Please Select -")*@
                                        @* @Html.DropDownList("Rol", ViewBag.Roles as List<SelectListItem>, new { @class = "form-control p-0" })*@
                                    </div>
                                </div>
                            </div>
                            <div style="text-align:left;">
                                <a href="~/HomeAdmin/"><button type="button" class="btn btn-danger">Cancelar</button></a>
                                <button type="submit" class="btn btn-success">Guardar</button>

                            </div>
                        </div>

                    </div>
                }
            </div>
        </div>
    </div>
</div>

SistemaMedico/Views/HomeAdmin/Index.cshtml
@*@model SistemaMedico.Models.Usuario*@
@using SistemaMedico.Models
@{
    ViewBag.Title = "Lista de Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //if (Session["ID"] == null)
    //{
    //    Response.Redirect("~/Login/Index");
    //}
    IEnumerable<Usuarios> Usuarios = (IEnumerable<Usuarios>)ViewBag.Usuario;
    var variable = 1;
}
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2 style="text-transform:uppercase;">@ViewBag.Title</h2>
            </div>
            <div class="body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>#</th>
                                        <th>Usuario</th>
                                        <th>Correo</th>
                                        @* <th>Password</th>*@
                                        <th>Acciones</th>
                                    </tr>
                                </thead>

                                @foreach (Usuarios oElemento in Usuarios)
                                {
                                    <tr>
                                        <td>@variable</td>
                                        <td>@oElemento.Nombre</td>
                                        <td>@oElemento.Correo</td>
                                        @*<td>@oElemento.Contraseña</td>*@
                                        <td>
                                            <a href="~/HomeAdmin/Editar/@oElemento.ID" class="btn bg-orange btn-circle waves-effect waves-circle waves-float">
                                                <i class="material-icons">mode_edit</i>
                                            </a>
                                            <a href="~/HomeAdmin/Eliminar/@oElemento.ID" class="btn bg-red btn-circle waves-effect waves-circle waves-float">
                                                <i class="material-icons">delete</i>
                                            </a>
                                        </td>
                                    </tr>
                                    variable++;

                                }

                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SistemaMedico/Views/HomeAdmin/Nuevo.cshtml
@model SistemaMedico.Models.ViewModel.UsuarioViewModel
@{
    ViewBag.Title = "Nuevo Usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //if (Session["ID"] == null)
    //{
    //    Response.Redirect("~/Login/Index");
    //}
    //IEnumerable<Usuario> Usuarios = (IEnumerable<Usuario>)ViewBag.Usuario;
}
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2 style="text-transform:uppercase;">@ViewBag.title </h2>
            </div>
            <div class="body">
                @using (Html.BeginForm("Nuevo", "HomeAdmin", FormMethod.Post))
                {
                    <div class="row">
                        <div class="col-md-12">
                            @*@Html.HiddenFor(d => d.ID)*@
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            @Html.LabelFor(d => d.Nombre, new { @class = "form-label" })
                                            @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>

                                @*@Html.ValidationMessageFor(d => d.UserName, null, new { @class = "red" })*@
                            </div>
                            @* Correo *@
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            @Html.LabelFor(d => d.Correo, new { @class = "form-label" })
                                            @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "red" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @* Contraeña *@
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            @Html.LabelFor(d => d.Contraseña, new { @class = "form-label" })
                                            @Html.PasswordFor(d => d.Contraseña, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(d => d.Contraseña, null, new { @class = "danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-float">

                                        @Html.Label("Rol") <br />
                                        @Html.DropDownListFor(x => x.ID_Rol, SistemaMedico.Controllers.HomeAdminController.GetDropDown(), new { @class = "form-control p-0" })
                                        @*@Html.DropDownListFor(d => d.ID_Rol, new SelectList(ViewBag.Roles, "Value", "Text"), new { @class = "form-control p-0" })*@
                                        @*@Html.DropDownListFor(model => model.ID_Rol, ViewBag.Roles as List<SelectListItem>, "ID", "Rol", "- Please Select -")*@
                                        @* @Html.DropDownList("Rol", ViewBag.Roles as List<SelectListItem>, new { @class = "form-control p-0" })*@
                                    </div>
                                </div>
                            </div>
                            <div style="text-align:left;">
                                <a href="~/HomeAdmin/"><button type="button" class="btn btn-danger">Cancelar</button></a>
                                <button type="submit" class="btn btn-success">Guardar</button>

                            </div>
                        </div>

                    </div>
                }
            </div>
        </div>
    </div>
</div>

SistemaMedico/Views/HomeAdmin/Vista.cshtml
@model SistemaMedico.Models.Usuarios
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["ID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}

<h2>View</h2>